[package]
name = "htool2"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# iced = "0.4.2"
image = "0.24.2"
# img_hash = "3.2.0"
# pihash = "0.5.0"
image_hasher = "1.0.0"
hex = "0.4.3"
sha256 = "1.0.3"
custom_error = "1.9.2"
figment = { version = "0.10.6", features = ["toml", "env"] }
serde = "1.0.137"
path-absolutize = "3.0.13"
toml = "0.5.9"
thiserror = "1.0"
# config = "0.13.1"
anyhow = "1.0"
eframe = "0.18.0"
rfd = "0.8.4"
egui_extras = "0.18.0"
poll-promise = "0.1.0"