[package]
name = "htool2"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
image_hasher = "1.0.0"
hex = "0.4.3"
sha256 = "1.0.3"
custom_error = "1.9.2"
figment = { version = "0.10.6", features = ["toml", "env"] }
serde = "1.0.137"
path-absolutize = "3.0.13"
toml = "0.5.9"
thiserror = "1.0"
rand = "0.8.5"
anyhow = "1.0"
eframe = "0.19.0"
rfd = "0.10.0"
crossbeam-utils = "0.8.9"
egui_extras = "0.19.0"
poll-promise = "0.1.0"
infer = "0.9.0"
chrono = "0.4.22"
downcast-rs = "1.2.0"
rusqlite = { version = "0.28.0", features = ["bundled", "blob"] }
egui-notify = { git = "https://github.com/n00kii/egui-notify" }
egui-modal = "0.1.4"

[profile.dev]
opt-level = 3