path:
  root: E:\root
  landing: F:\Media\Documents\Projects\htool2\htool2\testing_files
  database: data-test
general:
  entry_max_score: 5
  gallery_base_search: independant=true limit=5000
misc:
  entry_short_id_length: 6
ui:
  thumbnail_resolution: 100
  import_thumbnail_size: 63
  gallery_thumbnail_size: 50
  preview_pool_columns: 4
  preview_pool_size: 263
  preview_reorder_size: 543
  preview_size: 500
themes:
  current_theme: palenight
  themes:
  - name: palenight
    bg_fill_color: '#232635'
    secondary_bg_fill_color: '#232635'
    tertiary_bg_fill_color: '#1C1F2B'
    bg_stroke_width: null
    fg_stroke_width: null
    inactive_bg_fill_color: '#292D3E'
    inactive_bg_stroke_color: null
    inactive_fg_stroke_color: '#676E95'
    hovered_bg_fill_color: '#212532'
    hovered_bg_stroke_color: '#676E95'
    hovered_fg_stroke_color: '#A6ACCD'
    active_bg_fill_color: '#212532'
    active_bg_stroke_color: '#80CBC4'
    active_fg_stroke_color: '#80CBC4'
    selected_fg_stroke_color: '#80CBC4'
    selected_bg_fill_color: '#1C1F2B'
    blue_fill_color: null
    blue_stroke_color: '#82AAFF'
    red_fill_color: '#412A32'
    red_stroke_color: '#9C5560'
    green_fill_color: null
    green_stroke_color: null
    yellow_stroke_color: null
    yellow_fill_color: null
    accent_fill_color: '#203231'
    accent_stroke_color: '#80CBC4'
    override_widget_primary: '#80CBC4'
    override_widget_secondary: null
namespaces:
- name: artist
  color: '#686FD5'
- name: character
  color: '#915C55'
- name: copyright
  color: '#91D0CC'
- name: ref
  color: '#FFE326'
