path:
  root: D:/root
  landing: F:\Media\Documents\Projects\htool2\htool2\testing_files
  database: data1
general:
  entry_max_score: 5
  gallery_base_search: independant=true limit=5000
misc:
  entry_short_id_length: 6
ui:
  thumbnail_resolution: 100
  import_thumbnail_size: 63
  gallery_thumbnail_size: 50
  preview_pool_columns: 4
  preview_pool_size: 263
  preview_reorder_size: 543
  preview_size: 500
themes:
  current_theme: black
  themes:
  - name: eggplant
    bg_fill_color: '#814961'
    secondary_bg_fill_color: '#804961'
    tertiary_bg_fill_color: '#66374C'
    bg_stroke_width: null
    fg_stroke_width: null
    inactive_bg_fill_color: '#965671'
    inactive_bg_stroke_color: null
    inactive_fg_stroke_color: '#C4FAFA'
    hovered_bg_fill_color: '#945771'
    hovered_bg_stroke_color: null
    hovered_fg_stroke_color: '#A0FFFF'
    active_bg_fill_color: '#804961'
    active_bg_stroke_color: null
    active_fg_stroke_color: '#C4FAFA'
    selected_fg_stroke_color: '#C4FAFA'
    selected_bg_fill_color: '#804961'
    blue_fill_color: null
    blue_stroke_color: '#82AAFF'
    red_fill_color: '#813445'
    red_stroke_color: '#AD5D69'
    green_fill_color: null
    green_stroke_color: null
    yellow_stroke_color: null
    yellow_fill_color: null
    accent_fill_color: '#80CBC4'
    accent_stroke_color: '#203231'
    override_widget_primary: '#C4FAFA'
    override_widget_secondary: null
  - name: palenight
    bg_fill_color: '#232635'
    secondary_bg_fill_color: '#232635'
    tertiary_bg_fill_color: '#1C1F2B'
    bg_stroke_width: null
    fg_stroke_width: null
    inactive_bg_fill_color: '#292D3E'
    inactive_bg_stroke_color: null
    inactive_fg_stroke_color: '#676E95'
    hovered_bg_fill_color: '#212532'
    hovered_bg_stroke_color: '#676E95'
    hovered_fg_stroke_color: '#A6ACCD'
    active_bg_fill_color: '#212532'
    active_bg_stroke_color: '#80CBC4'
    active_fg_stroke_color: '#80CBC4'
    selected_fg_stroke_color: '#80CBC4'
    selected_bg_fill_color: '#1C1F2B'
    blue_fill_color: null
    blue_stroke_color: '#82AAFF'
    red_fill_color: '#412A32'
    red_stroke_color: '#9C5560'
    green_fill_color: null
    green_stroke_color: null
    yellow_stroke_color: null
    yellow_fill_color: null
    accent_fill_color: '#203231'
    accent_stroke_color: '#80CBC4'
    override_widget_primary: '#80CBC4'
    override_widget_secondary: null
  - name: black
    bg_fill_color: '#000000'
    secondary_bg_fill_color: '#000000'
    tertiary_bg_fill_color: '#000000'
    bg_stroke_width: null
    fg_stroke_width: null
    inactive_bg_fill_color: '#111111'
    inactive_bg_stroke_color: null
    inactive_fg_stroke_color: '#808080'
    hovered_bg_fill_color: '#1d1d1d'
    hovered_bg_stroke_color: '#333333'
    hovered_fg_stroke_color: '#b6b6b6'
    active_bg_fill_color: '#686868'
    active_bg_stroke_color: '#c5c5c5'
    active_fg_stroke_color: '#c5c5c5'
    selected_fg_stroke_color: '#dbdbdb'
    selected_bg_fill_color: '#272727'
    blue_fill_color: null
    blue_stroke_color: '#82AAFF'
    red_fill_color: '#2c1616'
    red_stroke_color: '#9c5555'
    green_fill_color: null
    green_stroke_color: null
    yellow_stroke_color: null
    yellow_fill_color: null
    accent_fill_color: '#3d3d3d'
    accent_stroke_color: '#dbdbdb'
    override_widget_primary: '#dbdbdb'
    override_widget_secondary: null
